### ISSUE TITLE
missing list of sample info

### ISSUE THREAD

**Issue by wenzhenl** [LUMC/ribosome-profiling-analysis-framework#1]
Hi,
After I downloaded data from ENA, it is so difficult to identify the samples, can you tell me how many replicates are used for RNA-seq, and for the files below, which ones are myoblasts and which ones are myotubes, thanks!
Tube_6157_T0B_standard_i10_TAGCTT_TAGCTT_L006_R1_001
Tube_6157_T0C_standard_i11_GGCTAC_GGCTAC_L006_R1_001
Tube_6157_T7B_standard_i14_AGCTTC_AGCTTC_L006_R1_001
Tube_6157_T7C_standard_i15_GTCAAC_GTCAAC_L006_R1_001

**Comment by ifokkema** [comment]
Hi there,

The T0 files are myoblasts, T7 are myotubes. We have two biological replicates per condition, B and C. From the study's file list, under the "Sample accession" column, you can find links that provide more information on each sample, such as treatment and differentiation time (under the "Attributes" tab).

Hope this helps!

**Comment by wenzhenl** [comment]
Thanks! It really helps!

**Comment by ifokkema** [comment]
You had also asked about using different samples for RNA-seq and the RP; Yes, they were from different samples and the way we normalized the data is different from the method of Ingolia, that's why it doesn't matter if they are from the same sample or not). Hope this helps!

**Comment by wenzhenl** [comment]
Really helps! Thanks a lot!
