### ISSUE TITLE
Failed to find CDS error from generate_stats_peaks_per_location.php

### ISSUE THREAD

**Issue by liyangyang12** [LUMC/ribosome-profiling-analysis-framework#3]
Hi，I'd like to ask you a question about generate_stats_peaks_per_location.php, when I use it, it failed with information "Failed to find CDS for NC_000074.6:F:117256727:NM_001163262.1",How can I solve it?
Look forward to your answer ! Thank  you!

**Comment by ifokkema** [comment]
Hi there,
It seems this transcript is very very long, and the NC slice that got downloaded doesn't fully contain this NM. You can do two things:

- Change the `NC_slice_length` setting in `generate_stats_peaks_per_location.php` from 75000 to 210000 (large enough for this transcript) and remove the `NC_000074.6:F:117256727.gb` from your cache directory so it gets downloaded again. This will make all future NC downloads much, much larger (and slower), but it will fix this error and any possible future similar errors.

- Or, you can manually download `http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000074.6&strand=1&seq_start=117256727&seq_stop=117465000&rettype=gb` and save that file as `NC_000074.6:F:117256727.gb`. That will fix this error, but won't prevent possible other errors of the similar origin to show up.

Hope this helps!
